<?php

// autoload_classmap.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'ArraySubscriptionVendors\\JG\\Config\\Config' => $vendorDir . '/jamesgober/config/src/Config.php',
    'ArraySubscriptionVendors\\JG\\Config\\ConfigParserFactory' => $vendorDir . '/jamesgober/config/src/ConfigParserFactory.php',
    'ArraySubscriptionVendors\\JG\\Config\\Exceptions\\ConfigException' => $vendorDir . '/jamesgober/config/src/Exceptions/ConfigException.php',
    'ArraySubscriptionVendors\\JG\\Config\\Exceptions\\ConfigParseException' => $vendorDir . '/jamesgober/config/src/Exceptions/ConfigParseException.php',
    'ArraySubscriptionVendors\\JG\\Config\\Exceptions\\InvalidParserException' => $vendorDir . '/jamesgober/config/src/Exceptions/InvalidParserException.php',
    'ArraySubscriptionVendors\\JG\\Config\\Parsers\\ConfParser' => $vendorDir . '/jamesgober/config/src/Parsers/ConfParser.php',
    'ArraySubscriptionVendors\\JG\\Config\\Parsers\\IniParser' => $vendorDir . '/jamesgober/config/src/Parsers/IniParser.php',
    'ArraySubscriptionVendors\\JG\\Config\\Parsers\\JsonParser' => $vendorDir . '/jamesgober/config/src/Parsers/JsonParser.php',
    'ArraySubscriptionVendors\\JG\\Config\\Parsers\\ParserInterface' => $vendorDir . '/jamesgober/config/src/Parsers/ParserInterface.php',
    'ArraySubscriptionVendors\\JG\\Config\\Parsers\\PhpParser' => $vendorDir . '/jamesgober/config/src/Parsers/PhpParser.php',
    'ArraySubscriptionVendors\\JG\\Config\\Parsers\\XmlParser' => $vendorDir . '/jamesgober/config/src/Parsers/XmlParser.php',
    'ArraySubscriptionVendors\\JG\\Config\\Parsers\\YamlParser' => $vendorDir . '/jamesgober/config/src/Parsers/YamlParser.php',
    'ArraySubscriptionVendors\\Psr\\Http\\Message\\MessageInterface' => $vendorDir . '/psr/http-message/src/MessageInterface.php',
    'ArraySubscriptionVendors\\Psr\\Http\\Message\\RequestInterface' => $vendorDir . '/psr/http-message/src/RequestInterface.php',
    'ArraySubscriptionVendors\\Psr\\Http\\Message\\ResponseInterface' => $vendorDir . '/psr/http-message/src/ResponseInterface.php',
    'ArraySubscriptionVendors\\Psr\\Http\\Message\\ServerRequestInterface' => $vendorDir . '/psr/http-message/src/ServerRequestInterface.php',
    'ArraySubscriptionVendors\\Psr\\Http\\Message\\StreamInterface' => $vendorDir . '/psr/http-message/src/StreamInterface.php',
    'ArraySubscriptionVendors\\Psr\\Http\\Message\\UploadedFileInterface' => $vendorDir . '/psr/http-message/src/UploadedFileInterface.php',
    'ArraySubscriptionVendors\\Psr\\Http\\Message\\UriInterface' => $vendorDir . '/psr/http-message/src/UriInterface.php',
    'ArraySubscriptionVendors\\Symfony\\Component\\Yaml\\Command\\LintCommand' => $vendorDir . '/symfony/yaml/Command/LintCommand.php',
    'ArraySubscriptionVendors\\Symfony\\Component\\Yaml\\Dumper' => $vendorDir . '/symfony/yaml/Dumper.php',
    'ArraySubscriptionVendors\\Symfony\\Component\\Yaml\\Escaper' => $vendorDir . '/symfony/yaml/Escaper.php',
    'ArraySubscriptionVendors\\Symfony\\Component\\Yaml\\Exception\\DumpException' => $vendorDir . '/symfony/yaml/Exception/DumpException.php',
    'ArraySubscriptionVendors\\Symfony\\Component\\Yaml\\Exception\\ExceptionInterface' => $vendorDir . '/symfony/yaml/Exception/ExceptionInterface.php',
    'ArraySubscriptionVendors\\Symfony\\Component\\Yaml\\Exception\\ParseException' => $vendorDir . '/symfony/yaml/Exception/ParseException.php',
    'ArraySubscriptionVendors\\Symfony\\Component\\Yaml\\Exception\\RuntimeException' => $vendorDir . '/symfony/yaml/Exception/RuntimeException.php',
    'ArraySubscriptionVendors\\Symfony\\Component\\Yaml\\Inline' => $vendorDir . '/symfony/yaml/Inline.php',
    'ArraySubscriptionVendors\\Symfony\\Component\\Yaml\\Parser' => $vendorDir . '/symfony/yaml/Parser.php',
    'ArraySubscriptionVendors\\Symfony\\Component\\Yaml\\Tag\\TaggedValue' => $vendorDir . '/symfony/yaml/Tag/TaggedValue.php',
    'ArraySubscriptionVendors\\Symfony\\Component\\Yaml\\Unescaper' => $vendorDir . '/symfony/yaml/Unescaper.php',
    'ArraySubscriptionVendors\\Symfony\\Component\\Yaml\\Yaml' => $vendorDir . '/symfony/yaml/Yaml.php',
    'ArraySubscriptionVendors\\Symfony\\Polyfill\\Ctype\\Ctype' => $vendorDir . '/symfony/polyfill-ctype/Ctype.php',
    'Composer\\InstalledVersions' => $vendorDir . '/composer/InstalledVersions.php',
);
