<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitef21e5a65b6c33101090558ed18180e1
{
    public static $files = array (
        '6e3fae29631ef280660b3cdad06f25a8' => __DIR__ . '/..' . '/symfony/deprecation-contracts/function.php',
        '320cde22f66dd4f5d3fd621d3e88b98f' => __DIR__ . '/..' . '/symfony/polyfill-ctype/bootstrap.php',
    );

    public static $prefixLengthsPsr4 = array (
        'A' => 
        array (
            'ArraySubscription\\' => 18,
            'ArraySubscriptionVendors\\Symfony\\Polyfill\\Ctype\\' => 48,
            'ArraySubscriptionVendors\\Symfony\\Component\\Yaml\\' => 48,
            'ArraySubscriptionVendors\\Psr\\Http\\Message\\' => 42,
            'ArraySubscriptionVendors\\JG\\Config\\' => 35,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'ArraySubscription\\' => 
        array (
            0 => __DIR__ . '/../..' . '/src',
        ),
        'ArraySubscriptionVendors\\Symfony\\Polyfill\\Ctype\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/polyfill-ctype',
        ),
        'ArraySubscriptionVendors\\Symfony\\Component\\Yaml\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/yaml',
        ),
        'ArraySubscriptionVendors\\Psr\\Http\\Message\\' => 
        array (
            0 => __DIR__ . '/..' . '/psr/http-message/src',
        ),
        'ArraySubscriptionVendors\\JG\\Config\\' => 
        array (
            0 => __DIR__ . '/..' . '/jamesgober/config/src',
        ),
    );

    public static $classMap = array (
        'ArraySubscriptionVendors\\JG\\Config\\Config' => __DIR__ . '/..' . '/jamesgober/config/src/Config.php',
        'ArraySubscriptionVendors\\JG\\Config\\ConfigParserFactory' => __DIR__ . '/..' . '/jamesgober/config/src/ConfigParserFactory.php',
        'ArraySubscriptionVendors\\JG\\Config\\Exceptions\\ConfigException' => __DIR__ . '/..' . '/jamesgober/config/src/Exceptions/ConfigException.php',
        'ArraySubscriptionVendors\\JG\\Config\\Exceptions\\ConfigParseException' => __DIR__ . '/..' . '/jamesgober/config/src/Exceptions/ConfigParseException.php',
        'ArraySubscriptionVendors\\JG\\Config\\Exceptions\\InvalidParserException' => __DIR__ . '/..' . '/jamesgober/config/src/Exceptions/InvalidParserException.php',
        'ArraySubscriptionVendors\\JG\\Config\\Parsers\\ConfParser' => __DIR__ . '/..' . '/jamesgober/config/src/Parsers/ConfParser.php',
        'ArraySubscriptionVendors\\JG\\Config\\Parsers\\IniParser' => __DIR__ . '/..' . '/jamesgober/config/src/Parsers/IniParser.php',
        'ArraySubscriptionVendors\\JG\\Config\\Parsers\\JsonParser' => __DIR__ . '/..' . '/jamesgober/config/src/Parsers/JsonParser.php',
        'ArraySubscriptionVendors\\JG\\Config\\Parsers\\ParserInterface' => __DIR__ . '/..' . '/jamesgober/config/src/Parsers/ParserInterface.php',
        'ArraySubscriptionVendors\\JG\\Config\\Parsers\\PhpParser' => __DIR__ . '/..' . '/jamesgober/config/src/Parsers/PhpParser.php',
        'ArraySubscriptionVendors\\JG\\Config\\Parsers\\XmlParser' => __DIR__ . '/..' . '/jamesgober/config/src/Parsers/XmlParser.php',
        'ArraySubscriptionVendors\\JG\\Config\\Parsers\\YamlParser' => __DIR__ . '/..' . '/jamesgober/config/src/Parsers/YamlParser.php',
        'ArraySubscriptionVendors\\Psr\\Http\\Message\\MessageInterface' => __DIR__ . '/..' . '/psr/http-message/src/MessageInterface.php',
        'ArraySubscriptionVendors\\Psr\\Http\\Message\\RequestInterface' => __DIR__ . '/..' . '/psr/http-message/src/RequestInterface.php',
        'ArraySubscriptionVendors\\Psr\\Http\\Message\\ResponseInterface' => __DIR__ . '/..' . '/psr/http-message/src/ResponseInterface.php',
        'ArraySubscriptionVendors\\Psr\\Http\\Message\\ServerRequestInterface' => __DIR__ . '/..' . '/psr/http-message/src/ServerRequestInterface.php',
        'ArraySubscriptionVendors\\Psr\\Http\\Message\\StreamInterface' => __DIR__ . '/..' . '/psr/http-message/src/StreamInterface.php',
        'ArraySubscriptionVendors\\Psr\\Http\\Message\\UploadedFileInterface' => __DIR__ . '/..' . '/psr/http-message/src/UploadedFileInterface.php',
        'ArraySubscriptionVendors\\Psr\\Http\\Message\\UriInterface' => __DIR__ . '/..' . '/psr/http-message/src/UriInterface.php',
        'ArraySubscriptionVendors\\Symfony\\Component\\Yaml\\Command\\LintCommand' => __DIR__ . '/..' . '/symfony/yaml/Command/LintCommand.php',
        'ArraySubscriptionVendors\\Symfony\\Component\\Yaml\\Dumper' => __DIR__ . '/..' . '/symfony/yaml/Dumper.php',
        'ArraySubscriptionVendors\\Symfony\\Component\\Yaml\\Escaper' => __DIR__ . '/..' . '/symfony/yaml/Escaper.php',
        'ArraySubscriptionVendors\\Symfony\\Component\\Yaml\\Exception\\DumpException' => __DIR__ . '/..' . '/symfony/yaml/Exception/DumpException.php',
        'ArraySubscriptionVendors\\Symfony\\Component\\Yaml\\Exception\\ExceptionInterface' => __DIR__ . '/..' . '/symfony/yaml/Exception/ExceptionInterface.php',
        'ArraySubscriptionVendors\\Symfony\\Component\\Yaml\\Exception\\ParseException' => __DIR__ . '/..' . '/symfony/yaml/Exception/ParseException.php',
        'ArraySubscriptionVendors\\Symfony\\Component\\Yaml\\Exception\\RuntimeException' => __DIR__ . '/..' . '/symfony/yaml/Exception/RuntimeException.php',
        'ArraySubscriptionVendors\\Symfony\\Component\\Yaml\\Inline' => __DIR__ . '/..' . '/symfony/yaml/Inline.php',
        'ArraySubscriptionVendors\\Symfony\\Component\\Yaml\\Parser' => __DIR__ . '/..' . '/symfony/yaml/Parser.php',
        'ArraySubscriptionVendors\\Symfony\\Component\\Yaml\\Tag\\TaggedValue' => __DIR__ . '/..' . '/symfony/yaml/Tag/TaggedValue.php',
        'ArraySubscriptionVendors\\Symfony\\Component\\Yaml\\Unescaper' => __DIR__ . '/..' . '/symfony/yaml/Unescaper.php',
        'ArraySubscriptionVendors\\Symfony\\Component\\Yaml\\Yaml' => __DIR__ . '/..' . '/symfony/yaml/Yaml.php',
        'ArraySubscriptionVendors\\Symfony\\Polyfill\\Ctype\\Ctype' => __DIR__ . '/..' . '/symfony/polyfill-ctype/Ctype.php',
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitef21e5a65b6c33101090558ed18180e1::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitef21e5a65b6c33101090558ed18180e1::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInitef21e5a65b6c33101090558ed18180e1::$classMap;

        }, null, ClassLoader::class);
    }
}
