<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'ArraySubscription\\' => array($baseDir . '/src'),
    'ArraySubscriptionVendors\\Symfony\\Polyfill\\Ctype\\' => array($vendorDir . '/symfony/polyfill-ctype'),
    'ArraySubscriptionVendors\\Symfony\\Component\\Yaml\\' => array($vendorDir . '/symfony/yaml'),
    'ArraySubscriptionVendors\\Psr\\Http\\Message\\' => array($vendorDir . '/psr/http-message/src'),
    'ArraySubscriptionVendors\\JG\\Config\\' => array($vendorDir . '/jamesgober/config/src'),
);
